---
all:
  children:
    home:
      hosts:
        trastero02:
          ansible_host: 192.168.8.3
          ansible_user: root
        rpi4:
          ansible_host: 192.168.8.4
          ansible_user: pi
        rpi3:
          ansible_host: 192.168.8.5
          ansible_user: pi
    proxmox:
      hosts:
        trastero01:
          ansible_host: 192.168.8.2
          ansible_user: root
    oci:
      hosts:
        oci-madrid:
          ansible_host: 158.179.209.39
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /root/.oci/oci-key
        oci-frankfurt:
          ansible_host: 130.61.106.137
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /root/.oci/oci-key

